PostReview/postreview-app

app/core/components/Features.tsx, app/pages/index.tsx
This PR moves the features information on the landing page on top, below the hero.
- rename NotConvincedYet to Features
- update component name
=> move features on top

app/core/hooks/useCurrentUser.ts
This PR updates the query to set the retry attempts for the getCurrentUser query to 3
=> set retry to 3

app/core/components/PopupReview.tsx, app/core/components/ReviewList.tsx, app/pages/articles/[articleId].tsx, app/pages/profile.tsx
This PR fixes the reference to blitz as "blitz", rather than "@blitz". With the blitz.js update, import references are no longer "@blitz".
=> fix reference to blitz module

app/api/auth/[...auth].ts
This PR makes the google callback URL defined by an environmental variable so that I can use the strategy at local and also on Heroku.
=> Use GOOGLE_CALLBACK_URL for OAuth strategy

app/mutations/deleteUser.tsx, app/pages/profile.tsx, db/migrations/20220103135507_allow_null_for_added_by_id/migration.sql, db/migrations/20220103135734_allow_null_user_for_review_answers/migration.sql, db/migrations/20220104111659_cascading_delete/migration.sql, db/schema.prisma
This PR adds a function to delete one's own account.
I'm using cascading delete here for review answers--so that people's reviews will be deleted as they delete their account. All the articles posted by a user will remain in the database, and the user field will be null.
- Make "addedBy" optional to allow null
- Add deleteUser mutation
- Add deleteUser to Profile
- Change the deactivate button
- Add Avatar to Profile
- Allow null for addedByID
- DB Migration
- Allow null user for ReviewAnswers
- db migration
- Cascade only for reviews, not for articles
- Bring out delete-account from Box
- Add logout mutation after deleteUser
=> add delete user

app/queries/getReviewAnswersByUserId.tsx
This PR fixes #53, the issue about the profile page showing articles without reviews. I fixed it using `some: {}` ([reference](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries)).
=> Change query to return only articles with user reviews

app/core/components/Article.tsx
This PR fixes #67. The problem was that the props for the getArticleScoresById query had the wrong argument (and thus querying multiple articles).
I also fixed #71 by making the DOI clickable. Along the way, I made the DOI line not break (via Tailwind, `whitespace-nowrap`)
- Make DOI clickable (fix 71)
- Fix key for the getArticleScoresByID
- Cleanup
- Do not wrap the DOI string and the icon
=> 67 Fix Duplicate Summary Scores

app/core/components/MyReviewsTable.tsx, app/core/components/ReviewList.tsx, app/pages/profile.tsx, app/queries/getReviewAnswersByUserId.tsx, app/queries/getUsersWithReviewsByArticleId.tsx
This PR fixes the issue of duplicate ratings appearing on profiles (Issue #88). 
I also fixed an unreported issue on duplicate ratings appearing on the article page.
- Fix article page reviews rendering
- Update query on profile to filter by user id
- Show handle if displayname is not set
=> 88 Fix duplicate ratings on profile & article page

app/core/components/MyReviewsEmptyState.tsx, app/core/components/RatePaperEmptyState.tsx, app/pages/profile.tsx, app/queries/getReviewAnswersByUserId.tsx
This PR removes an empty state ("Rate a Paper") from the profile page (fixes #75). 
Along the way, I also fixed a bug where I was seeing an article with a review on my profile, although I don't have reviews.
- Rename object for articles with review for a given user
- Make the query results null for articles without reviews
- Create an empty state for rate a paper
- Remove rate a paper from profile empty state
=> 75 Remove Empty State from the Profile Page

app/core/components/Article.tsx, app/core/components/PopupReview.tsx, app/core/components/ReviewQuestion.tsx, app/mutations/addReview.tsx, app/pages/articles/[articleId].tsx, app/queries/getReviewAnswersByArticleAndUserIds.tsx
This PR adds the functionality of modifying and updating reviews. Also, it subsequently fixes the infinite loading animation issue. Fixes #87 & #86 
Along the way, I also changed how the confirmation dialog is displayed for canceling out the review submission. Now, the confirmation window will only show up when the user clicked on the stars.
- Fix passing of user id to query
- Show existing review answers
- Make the rating value optional
- Use upsert for updating the reviews
- Hide the confirmation dialog if no change was made
- Fix nested a tag error
=> #87 Fix the review update process (modifying and updating reviews)

app/core/components/EnterDOI.tsx
This PR fixes the issue where we cannot add a paper for missing a journal title (fix #73). The cause of the problem was that some article metadata do not have `short-container-title`.
This PR also fixes the issue of author names appearing with extra commas (fix #66). This was because of the `.toString` adding commas between array elements. I changed it to `.join("")` to avoid this behavior. In the future, it's better to have a separate table for article authors for lookup, etc. 
- Get journal title from `container-title`
- Remove automatically generated commas in authors
=> 73 Fix the missing journal error when adding a paper

app/core/components/Footer.tsx
This PR adds a link to the code of conduct to the footer. 
Fixes #112
=> Add a link to the code of conduct to the footer

app/core/components/MyReviewsTable.tsx, app/core/components/PopupReview.tsx, app/core/components/ReviewQuestion.tsx, app/mutations/addReview.tsx, app/mutations/changeReivewAnonimity.tsx, app/mutations/deleteReview.tsx, app/pages/profile.tsx
This PR updates the action menu on the profile page, so that people can edit, change anonymity, or delete their reviews.
When the review is non-anonymous:
When the review is already anonymous:
@coglebed : I'm not sure "Show Your Name" is the best phrase there. Let me know if you can think of a better language 👋 
Fixes #103 
- Implement delete review on profile
- Add a confirmation dialog for deleting reviews
- Use MUI Button on the profile
- Show anonymity status on the review card
- Fix review mutation to handle anonymity
- Make the anonymous button controlled
- Implement a review popup on the profile page
- Add anonymous boolean to handle rating change
- Pass `userHasReview` to PopupReview
- Show "Update" when updating a review
- Cleanup code
- Add a db mutation to change anonymity
- …
=> Update the action menu for the reviews on the profile page

app/core/components/ArticleAction.tsx, app/core/components/MyReviewsTable.tsx, app/pages/profile.tsx
This PR fixes the problem where we can only perform actions (edit, make anonymous, delete) on the last article on the profile page (fixes #125).
The underlying problem was that the action menus etc were being rendered for all the articles at the same time. The solution is to separate a component for rendering a button and corresponding dialog boxes.
- Use the state hook to control articles with review
- Separate the article action menu
Side note: While working on this issue, I realized places where we can use the react state hook instead of reloading a page. Opened an issue for a future enhancement (#126).
=> Fix the profile page actions

app/pages/articles/[articleId].tsx
This PR disables the automatic popup for the review dialog for papers with no reviews. Fixing #106
=> Disable the automatic popup review dialogue

app/core/components/ReviewQuestion.tsx, app/pages/articles/[articleId].tsx
This PR avoids 400 (fix #85) via making the star rating controlled component and handling empty question answers.
=> Avoid 400 by controlling the star and handling empty question answers 

app/core/components/MyReviewsTable.tsx, app/core/components/Review.tsx, app/core/components/ReviewList.tsx, app/mutations/changeDisplayName.tsx, app/mutations/changeEmail.tsx, app/mutations/changeUserHandle.tsx, app/pages/profile.tsx
This PR adds functionality to change a user handle and a user's display name on the profile page (fix #74). I did not add functionality to change the user's email since it is currently tied to Google OAuth. Need to pick it up when we have an in-house sign-on function.
This PR also includes a small fix to show handles with `@` prefix. And a bugfix where the display name was passed as a handle on the article page.
=> Add functionality to change the handle and display name on the profile page

app/core/components/Article.tsx, app/queries/getArticleScoresById.tsx
This PR fixes the chip for the article card so that it shows the number of users with a review.
This PR also includes a small change in naming a prop for the `getArticleScoresById` query, so that the queries have a consistent name for the input article ID (`currentArticleId`).
=> Show the number of users with ratings in the chip for the article card

app/core/components/Article.tsx
This PR shows the aggregated rating scores on top of the starts on the article card. Previously, the stars did not have numbers on them (fixes #135).
=> Show rating values on top of the stars on the article card

app/core/components/Header.tsx, app/core/components/MyReviewsTable.tsx, app/pages/profile.tsx
This PR replaces the `<a>` tag with `<Link>` whenever possible. Fixes #167.
=> Use the Link component throughout the app

app/auth/mutations/signup.ts, app/auth/pages/signup.tsx
This PR modifies the DB mutation on signup so that the information about the newly-created user will be uploaded to Algolia. 
Fixes #180 
We still need to update the indices on Algolia as mentioned in #181.
=> Add user info to Algolia on signup

app/core/components/Footer.tsx, app/pages/how-it-works.tsx
This PR adds a page showing how the app works (as in the landing page), so that logged-in users can still see how the app works. 
Fixes #131
=> Add the How It Works page

app/core/components/Article.tsx, app/core/styles/index.css
This PR modifies the article card design to fix the horizontal alignment issue—fixes #184.
The author and DOI are now justified to the right.
=> Modify the article card design to fix the horizontal alignment 

tailwind.config.js
This PR sets [Fira Sans](https://github.com/mozilla/Fira) as the default typeface. Fixes #179.
=> Set Fira Sans as the default typeface

app/mutations/addArticle.tsx, db/migrations/20220802230410_allow_optional_journal_names/migration.sql, db/schema.prisma, tailwind.config.js
This PR allows adding papers without a journal. This change will allow submissions from websites like PsyArxiv, where the CrossRef record for the journal field is blank. Fixes #197.
=> Allow adding papers without a journal

app/core/components/Autocomplete.tsx
This PR makes the Algolia Autocomplete component compatible with React 18. Fixes #208.
=> Make Autocomplete compatible with React 18

app/core/components/Footer.tsx
This PR fixes the footer bleeding to the right in a mobile mode. Fixes #213.
=> Fix footer bleeding to right

app/pages/articles/[articleId].tsx
This PR changes the max width for the title section of the article page. See attached picture
.
Fixes #243
=> Change max width for the title section of the article page-Sherlock

app/core/components/Review.tsx
This PR adds a space in between the review summaries. Fixes #245
=> Add space in between review summaries

app/pages/articles/[articleId].tsx, app/queries/getArticleScoresById.tsx
This PR adds an expanded summary view for the article page. 
This PR also adds a function that counts the number of responses for each category.
Fixes #239
=> Add expanded summary view for the article page

app/core/components/ArticleAction.tsx, app/core/components/Review.tsx, app/core/components/ReviewList.tsx
This PR renders the edit button (...) on the own review on the article page, so that users can edit their rating on the spot. 
Fixes #241.
=> Render edit button to own review on the article page

app/core/components/SearchResultArticle.tsx, app/core/styles/index.css
This PR changes the color of the highlight when a search result is hovered.
This PR also removes the components hit. 
Fixes #242
=> Recolor algolia search bar

app/pages/articles/[articleId].tsx
This PR fixes the issue of the "add article" button not showing up.
The procedure to recreate the problem was:
1. Log in
2. Navigate to an article with your review
3. Search and navigate to an article without any review
The problem should not be happening with this PR.
Fixes #252.
=> Show add article button when no user review or no review

app/core/components/Article.tsx, app/core/components/ArticleList.tsx, app/core/components/NavDots.tsx, app/core/styles/index.css, app/pages/index.tsx
This PR allows viewing articles through the summary scores by question categories. Fixes #270.
Currently,  a "Sort by" selection does not persist when the user changes the category:
https://user-images.githubusercontent.com/17035406/185762581-f2e36e3a-7ed1-437c-9a1e-593508190c26.mov
It would make sense for the sorting to persist even when the user moves from one category to another.
=> Allow toggle through the question categories on the all reviews page

app/pages/code-of-conduct.tsx
This PR fixes the color of the code of conduct page. I used sx to declare the values instead of className.
Fixes #295
=> Fix the code of conduct page

app/core/components/DrawerMenu.tsx, app/core/components/Navbar.tsx, app/pages/index.tsx
This PR will change the behavior when clicking home in the drawer, so that non-logged in user will see the list of articles. 
This was achieved by the URL query string: `?search=true`
Fixes #296.
=> Clicking Home when not logged in will show the list of articles

app/core/components/DrawerMenu.tsx
This PR use the absolute paths to link to the code of conduct page and the teams of use page.
Fixes #297.
=> Use absolute paths in the drawer to the code of conduct page and terms of use page

app/core/components/Navbar.tsx, app/pages/browse.tsx
This PR fixes the padding of the browse page.
This PR also adds the nav bar with a hidden search to the browse page.
Fixes #312
=> Fix the margin for the browse page

app/mutations/addReview.tsx, app/mutations/deleteReview.tsx, app/mutations/helpers/updateArticleIndex.tsx
This PR adds a routine to update the Algolia index when deleting a review. Fixes #318.
The updating routine is factored out as `app/mutations/helpers/updateArticleIndex.tsx`.
=> Update the Algolia index when deleting a review

app/auth/pages/forgot-password.tsx, app/auth/pages/login.tsx, app/auth/pages/reset-password.tsx, app/auth/pages/signup.tsx
This PR hides the search bar on the authentication(log-in, sign-up, forgot password, reset password) pages.
Fixes #311
=> Remove search bar for authentication pages

app/auth/pages/signup.tsx
This PR adds the consent to policies (Terms of Use, Privacy Policy, and Code of Conduct) section on the sign-up page.
This PR also changes the styling of the "email already in use" error message for more visibility.
Fixes #281
=> Add consent to policies on sign-up page

app/core/components/DrawerMenu.tsx, app/core/components/HeaderUserButton.tsx, app/core/components/Navbar.tsx
This PR adjusts the margin of the nav bar components so that the menu icon will have some breathing margins even with the log-in and sign-up buttons. Fixes #310.
=> Fix the margin of the search bar 

app/pages/code-of-conduct.tsx, app/pages/privacy-policy.tsx, app/pages/terms-of-use.tsx
This PR adds expand and collapse for the accordion components on the following pages:
1. Terms of use
2. Privacy policy
3. Code of conduct 
Fixes #305.
=> Add expand & collapse all to the terms, privacy policy, and the code of conduct pages' accordion components

app/core/components/DrawerMenu.tsx
This PR changes the order of the policies to alphabetical order.
Fixes #333
=> Reorder the policies list

app/core/styles/index.css, app/pages/about.tsx, app/pages/code-of-conduct.tsx, app/pages/privacy-policy.tsx, app/pages/terms-of-use.tsx, tailwind.config.js
This PR moves the click events of the accordions to the accordion summary component, instead of the whole accordion component. 
Fixes #342.
=> Move click events on the accordion to the accordion summary component (on policy pages)

app/core/components/NavDots.tsx
This PR adds tooltips for the navigation dots. Fixes #304.
=> Add tooltips for the navigation dots

app/auth/pages/login.tsx
This PR changes the styling for the error message on the log-in page for better visibility.
Fixes #349
Before:
After:
=> Change the styling for the error message on log-in page

app/core/components/MyReviewsEmptyState.tsx, app/pages/profiles/[handle].tsx
This PR changes the positioning of components for "no reviews state" on the public profile.
Fixes #358
=> Adjust the margins for no reviews state on the public profile

app/core/components/Article.tsx, app/core/components/ArticleSummaryScores.tsx, app/pages/articles/[articleId].tsx
This PR removes the blank stars and the expanded accordion on the article page when an article has no reviews. 
This PR also adds a call-to-action statement when an article has no reviews.
Fixes #360
=> Fix the no reviews state on the article page

app/api/auth/[...auth].ts
This PR fixes a bug where clicking the resend email button for users with Google Auth will throw an error, and potentially freeze up the app.
This PR marks the user's email as verified when using Google Auth.
This PR also includes a fix where Google Auth users may have invalid handles with white spaces. Now, their handles will be their display name without white spaces. 
Fixes #367.
=> Fix Google Auth email verification failing

app/core/components/EnterDOI.tsx, app/core/components/SearchResultArticle.tsx
This PR optimizes the response of the search bar by adding a wait before querying CrossRef, instead of querying CorssRef every keystroke. Fixes #372.
=> Optimize the search bar responsiveness

app/core/components/EnterDOI.tsx
This PR sets debounce to one second. Fixes #375.
=> Optimize the search bar performance by increasing debounce and disabling open-on-focus

app/core/components/ArticleAction.tsx, app/core/components/PopupReview.tsx, app/core/components/Review.tsx, app/core/components/ReviewList.tsx, app/pages/articles/[articleId].tsx
This PR fixes the following bugs:
1. A bug where users editing their reviews see "No 1" badge
2. A bug where users submitting all-null answers will see the "Thank-you" badge
Fixes #368.
=> Avoid showing the "No 1" thank-you badge for edits, and at all for reviews with all-null answers

app/core/components/DrawerMenu.tsx
This PR changes the color of the copyright on the drawer menu.
Fixes #388
=> Change the font color for copyright

app/core/components/MyReviewsTable.tsx, app/pages/profile.tsx, app/pages/profiles/[handle].tsx
This PR adds a fixed width for review containers on the public and private profile pages. 
Fixes #369
=> Fix skinny article container on profile

app/api/auth/[...auth].ts
This PR changes the callback URL for the Google OAuth from a hard-coded string to the `GOOGLE_CALLBACK_URL`. Fixes #399.
=> Use an env var for Google Callback URL

app/core/components/SearchResultUser.tsx
This PR fixes the issue of failing search (TypeError) by using the `AvatarIcon` component in search result hits. Fixes #401.
=> Use `AvatarIcon` component in search results

app/pages/about.tsx
This PR fixes the typo on the Our Story page from
"... a question peaked two scientists' minds."
to 
"... a question piqued two scientists' minds."
Fixes #405
=> Fix the word `peaked` to `piqued` on the Our Story page

app/auth/pages/signup.tsx, app/core/components/GoogleButton.tsx, app/pages/profile.tsx
This PR revises the Splitbee events for the Google OAuth, such that the events are now attached to the `<a>` tag.
This PR also adds Splitbee events for the deactivate account buttons.
=> Revise Splitbee events for the Google OAuth and deactivating account

app/core/components/EnterDOI.tsx
This PR add `mailto` field to the CrossRef query, to follow the recommendation by Crossref. I referred to [Tips for using the Crossref REST API](https://www.crossref.org/documentation/retrieve-metadata/rest-api/tips-for-using-the-crossref-rest-api/)
I was hoping that the speed of return query increases, which did not. Nevertheless, it's good to follow their recommendation. 
Fixes #416
=> Add the `mailto` field to CrossRef Query
