app/core/components/Article.tsx, app/core/components/HowItWorks.tsx, app/core/components/Review.tsx, app/core/components/ReviewCategoryAnswer.tsx
This PR updates the article card for the front page. Together wit the tweaks to the Review card component.
- redesign Article component
- add disabled to Review
- remove key props from ReviewCategoryAnswer
- add Article component
=> update article card

app/core/components/Article.tsx, app/core/components/ArticleList.tsx, app/core/components/ArticleSample.tsx, app/core/components/EnterDOI.tsx, app/core/components/HeaderUserButton.tsx, app/core/components/HowItWorks.tsx, app/core/components/IndividualReview.tsx, app/core/components/MyReviewsTable.tsx, app/core/components/ReviewList.tsx, app/pages/articles/[articleId].tsx, app/pages/index.tsx, app/queries/getArticleScoresById.tsx, app/queries/getArticles.tsx, app/queries/getArticlesWithScores.tsx, app/queries/getQuestionCategories.tsx, app/queries/getReviewAnswers.tsx, package-lock.json, package.json
This is a very long PR!
I set to update the article card and the changes went everywhere. Right now, each article card queries DB to get article information, which is not the most efficient way. But it works. I will need to look out for performance issues in the future.
- update prisma to fix ECONNREFUSED error
- update query to get review answers to grouped by users
- update query to include question information
- add IndividualReviews component
- update review list to use IndividualReviews
- display handle if anonymous mode is on
- add greybox for article information
- Add headings to the article page
- cleanup the code for showing edit rating
- Anonymous reviews are always be anonymous
- Move article-level review to article page
- make the action button compoenent
- clenup
- Separate …
=> update article page

app/core/components/HeaderUserButton.tsx, app/core/components/SearchBar.tsx
This PR fixes #40 
- remove fragment from search bar
- remove fragments from Menu
=> 40 fix fragments

app/core/components/PopupReview.tsx, app/core/components/ReviewQuestion.tsx, app/mutations/addReview.tsx
This PR implements the UI for the popup review component.
=> Update popup review UI

app/api/auth/[...auth].ts
This PR updates the target URL for the passport so that Anton can log in
=> Update the passport target URL

.github/ISSUE_TEMPLATE/bug-report.yaml
This PR edits the GitHub issue form in the following ways:
1. Ask to report the URL of the place with a bug
2. Ask for steps to reproduce
=> Edit GitHub issue form

.github/ISSUE_TEMPLATE/bug-report.yaml
This PR fixes the indentation in the Issue Form .yaml file.
=> Fix Issue Form 

app/core/components/EnterDOI.tsx, app/core/components/PopupReview.tsx, app/pages/articles/[articleId].tsx, app/queries/getArticle.tsx, package-lock.json, package.json
This PR will ask users to add their reviews after adding an article. Users visiting an article page without reviews will be asked to provide a review. When they cancel, they will be redirected to the home page. Fix for #47 
- Redirect to the article after adding
- Cleanup
- Relation query number of reviews per article
- Add @mui/lab for LoadingButton
- Add LoadingButton for submit
- Add confirm close dialogue to review popup
=> 47 Ask users to review article that they added

Procfile, db/seeds.ts, package-lock.json, package.json
This PR adds `npx blitz db seed` to the `Procfile` so that the database will get seeded upon deployment.
Fixes #81.
=> Seed database upon release

app/core/components/EnterDOI.tsx, db/seeds.ts, package-lock.json
This PR removes the Placeholder DOI from the search bar. Fixes #77
=> 77 Remove the Placeholder DOI from the Search Bar

app/core/components/Article.tsx
This PR changes the color of the article stars and adds fill to the background for increased readability. Fixes #79
=> 79 Change color of the stars & fill background

app/core/components/Footer.tsx
This PR adds a copyright date that automatically updates (thanks @chartgerink for the detailed solution in #70!). It also fixes the links to the social accounts (#69).
Fixes #70 and #69.
=> Add an updating copyright date and links to social accounts

app/core/components/Footer.tsx
This PR adds a Discord icon to the footer (fixes #113).
=> Add Discord icon to the footer

app/core/components/AddPaperPopup.tsx, app/core/components/Article.tsx, app/core/components/Autocomplete.tsx, app/core/components/EnterDOI.tsx, app/core/components/Header.tsx, app/core/components/SearchResultArticle.tsx, app/core/styles/index.css, app/mutations/addArticle.tsx, app/mutations/addReview.tsx, app/queries/getUsersWithReviewsByArticleId.tsx, blitz.config.ts, package-lock.json, package.json
This PR implements search by Aloglia and streamlines the paper submission process. Fixes #140 
I started off trying to make the search bar a catch-all place to search from our DB and the crossref API. However, because the CrossRef API is a bit slow to respond, users have to wait for a while, even though they are just searching on our database. I circumvented this issue by separating the search for our items in the search box, and the search in CrossRef in the popup for adding a review.
- Combine the search bar and the CrossRef search, so that the user can search papers and add papers if needed in the same place
- Streamline the data structure sent to Algolia to accommodate multiple versions of review questions.
=> Implement search by Algolia and streamline the paper submission

README.md
This PR adds instructions to reset and seed the database on Heroku into the README
=> Add instructions on how to reset and seed the database on Heroku

app/core/components/AddPaperPopup.tsx, app/core/components/Button.tsx, app/core/components/EnterDOI.tsx, app/core/components/HeaderUserButton.tsx, app/core/components/Hero.tsx, app/core/components/PopupReview.tsx, app/pages/articles/[articleId].tsx, app/pages/profile.tsx
This PR replaces the MUI buttons with the in-house buttons. The MUI buttons had strange issues with the Tailwind. By using in-house buttons, we can avoid the problem. 
Fixes #52 and #153
=> Replace MUI buttons with the in-house buttons

app/core/components/MyReviewsTable.tsx, app/core/components/Review.tsx, package-lock.json, package.json
This PR will add the Incognito Icon for indicating anonymity, fixing #145.
=> Use the Incognito Icon for indicating anonymity

app/core/components/ArticleList.tsx, app/core/components/Hero.tsx, app/pages/browse.tsx, app/pages/index.tsx, app/queries/getArticlesWithReview.tsx
This PR removes login-walling to view articles (fixes #156). This PR also hides articles without reviews ("NA") from the list (fixes #44).
=> Remove login-walling & hide articles without reviews on front-end

app/core/components/AddPaperPopup.tsx, app/core/components/MyReviewsTable.tsx, app/core/components/Review.tsx, app/pages/profile.tsx, app/pages/profiles/[handle].tsx, app/pages/profiles/[userId].tsx, app/queries/getReviewAnswersByUserId.tsx, app/queries/getUserInfo.tsx
This PR adds a public profile page. We may need to further improve the design. Fixes #76.
This PR also includes small error fixes 
1. Fix kebab-case error
2. Fix non-boolean attribute error
=> Add a public profile page

app/core/components/ReviewList.tsx, app/pages/profile.tsx
This PR fixes the problem of the avatars not showing up on the article page. Fixes #166.
=> Show avatar on the article page

app/core/components/EnterDOI.tsx, app/core/components/Header.tsx, app/core/components/Hero.tsx
This PR adds a search bar to the hero. 
Fixes #163.
=> Add a search bar to the hero

app/api/auth/[...auth].ts, app/auth/mutations/signup.ts, app/auth/pages/forgot-password.tsx, app/auth/pages/login.tsx, app/auth/pages/reset-password.tsx, app/auth/pages/signup.tsx, app/auth/validations.ts, app/core/components/Button.tsx, app/core/components/HeaderUserButton.tsx, app/core/components/MyReviewsTable.tsx, app/pages/_app.tsx, app/pages/index.tsx, app/pages/profile.tsx, db/migrations/20220425125659_cascading_delete_on_token/migration.sql, db/schema.prisma, mailers/forgotPasswordMailer.ts, package-lock.json, package.json
This PR implements an in-house sign-in system so that people without a Google account can sign in to the app. 
TODO: We still need to find a way to verify their email to prevent possible spam. 
Fixes #134.
Also fixes #174.
=> Can create an account and login in-house (without Google)

app/core/components/HeaderUserButton.tsx, app/pages/profile.tsx
This PR uses the UI Avatars to create avatars.
Fixes #190
=> Use UI avatars for avatar

app/core/components/MyReviewsTable.tsx, app/core/components/Review.tsx, app/pages/profiles/[handle].tsx
This PR uses UI avatars on the review card and the public profile view.
Fixes #190
=> Use more UI avatars

app/core/components/Article.tsx, app/core/components/ArticleList.tsx, app/core/createReplica.tsx, db/seeds.ts, package-lock.json, package.json
This PR adds the search page with the ability to sort articles by the number of reviews and the ratings.
Fixes #177.
TODO: Make sure that Algolia records are in sync with the database. (#187)
=> Add the search view with sort 

app/core/components/MyReviewsTable.tsx, app/core/components/PopupReview.tsx, app/core/components/Review.tsx, app/core/components/ReviewList.tsx, app/core/components/ReviewQuestion.tsx, app/mutations/addReviewComment.tsx, app/queries/getReviewAnswersByUserId.tsx, app/queries/getReviewCommentByArticleAndUserIds.tsx, app/queries/getUsersWithReviewsByArticleId.tsx, db/migrations/20220628124808_add_review_comments/migration.sql, db/migrations/20220706101106_add_anonymous_field_to_review_comments/migration.sql, db/schema.prisma
This PR adds a new feature to add comments to the reviews. Fixes #196.
=> Add a feature to add comments to to the reviews

app/pages/articles/[articleId].tsx
This PR adds a title to the article page. 
The format is "*article title* | PostReview". Fixes #226.
=> Add title to the article page

app/core/components/MyReviewsTable.tsx, app/core/components/Review.tsx, app/core/components/ReviewList.tsx, app/core/components/ReviewStars.tsx, app/pages/articles/[articleId].tsx
This PR redesigns the review summary card to match the Sherlock theme. This PR handles the dark and light modes. Fixes #236
=> Change the layout for the review summary card

app/core/components/Review.tsx, app/core/components/ReviewList.tsx, app/pages/articles/[articleId].tsx
This PR fixes the issue of not being able to submit reviews. Fixes #247. The root cause of the issue was that `session` prop was not passed to the popup review component. 
This PR also includes minor fixes to clear error messages regarding rendering nested components and giving functional components with refs.
=> Fix the issue of not being able to submit reviews

app/pages/articles/[articleId].tsx
This PR updates the style for the NA category rating stars. 
Fixes #250
=> Update the styles for NA category rating stars

app/pages/how-it-works.tsx
This PR updates the "how it works" page to handle dark and light modes. 
This PR adds background color to make all contents visible.
Fixes #254
=> Update how it works page

app/core/components/ProfileBgImage.tsx, app/core/components/ProfileInfo.tsx, app/pages/articles/[articleId].tsx, app/pages/profile.tsx, app/pages/profiles/[handle].tsx, app/queries/getReviewAnswersByUserId.tsx, app/queries/getUserInfo.tsx
This PR styles the public profile page into the Sherlock theme. Fixes #260.
=> Style the public profile page into the Sherlock theme

app/core/components/EnterDOI.tsx, app/core/styles/index.css, app/pages/browse.tsx
This PR redesigns the browse page to adapt the Sherlock theme.
Fixes #273
=> Redesign the browse page

app/core/components/HowItWorks.tsx, app/pages/index.tsx
This PR fixes the spacing for items in the how it works section. 
This PR also centers the items for bigger size screens. 
Fixes #279
=> Fix how it works section 

app/core/components/HowItWorks.tsx
This PR fixes the alignment of the steps section for the article page. Each step needed to be wrapped in a separate div. Fixes #286
=> Change the alignment to center the steps

app/core/components/ReviewQuestion.tsx, app/mutations/addReview.tsx, db/migrations/20220823025036_allow_null_review_responses/migration.sql, db/schema.prisma
This PR makes it possible to skip/delete review answers, making categories optional. Fixes #292.
=> Make it possible to skip and delete review answers

app/core/styles/index.css
This PR changes the html default color to our darkest gray color. 
Fixes #303
=> Change the html background color

app/pages/code-of-conduct.tsx, app/pages/terms-of-use.tsx
This PR fixes the external links in the policy(CoC and ToU) pages so that a new window opens when they are clicked.
Fixes #322
=> Fix external links

README.md, app/core/components/AvatarIcon.tsx, app/core/components/HeaderUserButton.tsx, app/core/components/ProfileEditDialog.tsx, app/core/components/ProfileInfo.tsx, app/core/components/Review.tsx, app/core/styles/index.css, app/mutations/changeAvatar.tsx, app/mutations/changeUserInfo.tsx, app/pages/profile.tsx, blitz.config.ts, package-lock.json, package.json
This PR makes it possible to edit one's avatar on the platform. Fixes #189.
The PR implements the Uploadcare's [react widget](https://github.com/uploadcare/react-widget).  It requires a public API key. `UPLOADCARE_PUBLIC_KEY`
=> Make it possible to edit one's avatar icon

app/core/styles/index.css, app/pages/about.tsx, tailwind.config.js
This PR makes the transition for the bounce ease in better.
This PR also fixes the CSS error of missing a closing argument.
Fixes #338
=> Ease in transition animation

app/auth/pages/forgot-password.tsx, app/auth/pages/login.tsx, app/auth/pages/reset-password.tsx, app/auth/pages/signup.tsx, app/auth/pages/verify-email/[code].tsx, app/core/components/ArticleList.tsx, app/core/components/LayoutLoader.tsx, app/core/layouts/Layout.tsx, app/pages/about.tsx, app/pages/articles/[articleId].tsx, app/pages/browse.tsx, app/pages/code-of-conduct.tsx, app/pages/how-it-works.tsx, app/pages/index.tsx, app/pages/mission-vision.tsx, app/pages/privacy-policy.tsx, app/pages/profile.tsx, app/pages/profiles/[handle].tsx, app/pages/team.tsx, app/pages/terms-of-use.tsx
@nsunami 
This is the design for the loading screen. Please apply it to the pages.
=> Design loading screen

app/core/components/ArticleMetadata.tsx, app/core/components/ArticleSummaryScores.tsx, app/core/components/PopupReview.tsx, app/core/components/ReviewQuestion.tsx, app/pages/articles/[articleId].tsx
This PR redesigns the review popup. Fixes #351.
=> Redesign the review popup 

app/core/layouts/Layout.tsx
This PR adds Splitbee to Head ([doc](https://splitbee.io/docs/embed-the-script)). Fixes #341
=> Add Splitbee to Head

app/core/components/DrawerMenu.tsx
This PR changes the accordion bg color from transparent to gray light.
Fixes #344
=> Change bg color to gray light

app/core/components/PopupReview.tsx
This PR fixes the issue of the thank you badge disappearing too fast.
Fixes #361
=> Set timeout for window reload

app/core/components/Article.tsx
This PR will show the full title of an article when the screen is wide. Fixes #315.
=> Show the article's full title when the screen is wide

app/core/layouts/Layout.tsx
This PR adds Crisp Chat to the app. Fixes #383.
=> Add Crisp Chat to the app

app/auth/mutations/signup.ts
This PR updates the Postmark script for sending the welcome email. Fixes #390.
=> Update the Postmark script for sending the welcome email

app/api/auth/[...auth].ts, app/auth/mutations/signup.ts, app/core/components/EnterDOI.tsx, app/core/components/SearchResultUser.tsx, app/mutations/changeAvatar.tsx, app/mutations/changeUserInfo.tsx, app/mutations/deleteUser.tsx, blitz.config.ts
This PR adds a function to search users in the app. Fixes #195.
This PR also implements updating of Algolia records when signing up, editing, or deleting user profiles.
=> Add user search

app/auth/pages/login.tsx, app/auth/pages/signup.tsx, app/core/components/PopupReview.tsx, app/core/components/onboarding/UploadYourPhoto.tsx, app/pages/articles/[articleId].tsx
This PR adds Splitbee event tracking attributes to the important events on the website (e.g., sign-up, posting reviews).
Fixes #395.
=> Add Splitbee event tracking attributes

app/core/components/DrawerMenu.tsx
This PR moves the on-click event to the buttons in the drawer menu. Fixes #397.
=> Move the on-click event to the buttons in the drawer menu 

app/pages/profiles/[handle].tsx
This PR adds a button to go back to one's own profile, when looking at one's own profile.
Fixes #408.
=> Add "Back to your own view" button

app/auth/pages/onboarding.tsx, app/auth/pages/signup.tsx, app/core/components/onboarding/UploadYourPhoto.tsx, app/pages/articles/[articleId].tsx
This PR redirects the user to the article on which that they clicked the "Add Review" button to initiate the sign-up process. Fixes #411.
=> Redirect to the article viewed before the sign-up

app/core/components/Review.tsx, package-lock.json, package.json
This PR adds an icon to reviews with a comment. Fixes #413.
=> Add an icon to reviews with a comment

app/core/components/Hero.tsx, app/pages/index.tsx
This PR shows the list of articles to the users not logged in. 
Fixes #418
=> Show the list of articles for the users not logged in
